spring:
  application:
    name: rider-service
  datasource:
    url: jdbc:postgresql://ep-holy-block-a8d98zmt-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_ABJ7yH1ivbcS
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  registerWithEureka: true
  fetchRegistry: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0